CREATE TABLE "user" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "email" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "status" "status" NOT NULL DEFAULT 'OK',
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TRIGGER user_on_update
BEFORE UPDATE ON "user"
FOR EACH ROW
EXECUTE PROCEDURE on_update();
