definitions:
  dto.UserLogin:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.UserRegister:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  util.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  util.Success:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: User this api to Login your account
      parameters:
      - description: login using data request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Error'
      summary: Login User
      tags:
      - accounts
  /user/register:
    post:
      consumes:
      - application/json
      description: User this api to Register your account
      parameters:
      - description: register using data request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Error'
      summary: Register User
      tags:
      - accounts
swagger: "2.0"
